### ISSUE TITLE
The "Create new mod" button is barely accessible and visible

### ISSUE THREAD

**Issue by Anixx** [ramensoftware/windhawk#115]
![изображение](https://github.com/ramensoftware/windhawk/assets/1271736/49aa8103-248e-4bd6-a406-dc956ae719f8)

One has to pixelhunt to click it.

**Comment by m417z** [comment]
It seems that you made some changes to the VSCodium settings, such as the menu appearing. If not, then perhaps it happened because of a bug, but I never encountered it and no other user reported it so far. I believe that existing Windhawk and removing the UI folder from appdata should resolve these issues.

**Comment by m417z** [comment]
I tried your settings [from here](https://github.com/ramensoftware/windhawk/issues/105#issuecomment-1731324472) but couldn't reproduce it. Are the settings now different?

**Comment by Anixx** [comment]
I did not change settings, but I adjusted the scale (Zoom). But the problem remains after zoom reset.

**Comment by Anixx** [comment]
After zoom reset it is currently half of the button visible. When zoomed out the problem becomes worse and eventually the button disappears.

**Comment by Anixx** [comment]
I renamed the UI folder, and now the button is visible well but there is no menu and I do not know how to get it mack. Some actions (like "Select all") are available only via pull-down menu and not via context menu.

**Comment by m417z** [comment]
The menu is supposed to be hidden. If you show it and click on various options, it makes sense that eventually stuff will break.

What's missing without the menu?

Regarding "Select all", where is it useful?

**Comment by Anixx** [comment]
[UIData.bak.zip](https://github.com/ramensoftware/windhawk/files/12922346/UIData.bak.zip)
This is the UIData with which the problem is visible.

**Comment by Anixx** [comment]
Select all is necessary when for instance I create a new mod and want to delete the example thumb. Or when I want to copy the entire mod into a new file so to make a new mod based on the previous one.

**Comment by Anixx** [comment]
Without menu, how to save or load a file?

**Comment by m417z** [comment]
For selecting all code while in development mode, it would make sense to have it in the right click menu, but Microsoft decided not to add it, we discussed that:
https://github.com/ramensoftware/windhawk/discussions/55#discussioncomment-5495511
Also, I thought developers would just use Ctrl+A.

For loading and saving a file, it's not supported, and I don't know what the menu does but possibly not what you expect, so it's a good thing that you don't have it.

**Comment by Anixx** [comment]
After the resetting the UI settings, now there is no such issue any more, even with menu and with zooming out.

**Comment by m417z** [comment]
> [UIData.bak.zip](https://github.com/ramensoftware/windhawk/files/12922346/UIData.bak.zip)
> This is the UIData with which the problem is visible.

The issue was caused by this option, which is unsupported:
```
"breadcrumbs.enabled": false
```

**Comment by Anixx** [comment]
I do not know how this option got modified.
